language: cpp
compiler:
    - gcc
before_install:
    - wget https://raw.githubusercontent.com/yast/yast-devtools/SLE-12-GA/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "yast2-devtools yast2-testsuite doxygen yast2-core-dev libxml2-dev"
script:
    - make -f Makefile.cvs
    - make
    - make check
    - sudo make install

